version: '3'
services:
  db:
    image: mariadb:bionic
    restart: always
    container_name: db.codetest
    hostname: db.codetest
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT}
      MYSQL_DATABASE: ${SQL_DB}
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_PASS}
    networks:
      - codetest
    ports:
      - 3306:3306 #for the local testing
    volumes:
      - "./_data:/var/lib/mysql"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
#  backend:
#    build:
#      context: ./backend
#      Dockerfile: Dockerfile
networks:
  codetest: 
    driver: "bridge"