// TODO ADD AUTH
//export const SIGN_IN = 'SIGN_IN';
//export const SIGN_OUT = 'SIGN_OUT';

export const CREATE_FACTOID = 'CREATE_FACTOID';
export const FETCH_FACTOIDS = 'FETCH_FACTOIDS';
export const FETCH_INTERESTS = 'FETCH_INTERESTS';
export const DELETE_FACTOID = 'DELETE_FACTOID';
export const EDIT_FACTOID = 'EDIT_FACTOID';
export const SELECTION_UPDATED = 'SELECTION_UPDATED';